apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ikup
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ikup
    app.kubernetes.io/part-of: jessica-test
  name: devfile-sample-ikup
  namespace: jforrest-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ikup
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ikup
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:100b6c9ecdaf5715085a80314608d1381e3f02f56f819655d0b152629f722a35
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
